# Copyright (C) 2023 Maxwell G <maxwell@gtmx.me>
# SPDX-License-Identifier: MIT

repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.35.1"
    hooks:
      - id: yamllint
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: "v0.13.0"
    hooks:
    - id: markdownlint-cli2
      require_serial: true
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.28.5"
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
  - repo: https://github.com/rhysd/actionlint
    rev: "v1.7.1"
    hooks:
      - id: actionlint-docker
        entry: docker.io/rhysd/actionlint:1.6.26
ci:
  skip:
    - actionlint-docker
